alineas abnt; genero orientador
filipebraida/monografia-latex pull request #1
Opened 2020-05-12 21:30 UTC by AulosRafael

2020-06-06 16:18 UTC, filipebraida commented on elementos-pretextuais/abreviaturas.tex
> +\begin{acronym}[xxxxxxx]
Realmente queria ter feito isso, mas faltou tempo

2020-06-06 16:27 UTC, filipebraida requested changes
Dá uma olhada nos meu comentários e vê oq acha.

2020-06-06 16:27 UTC, filipebraida commented on projetofinal-dcc.cls
> +\RequirePackage[printonlyused]{acronym}
Esses três são para o acronym? Talvez colocar um comentário para deixar no padrão.

2020-06-06 16:27 UTC, filipebraida commented on elementos-postextuais/apendice.tex
> +Seguindo a Definição \ref{def:def1} e Teorema \ref{the:the1}.
Aqui uma boa é colocar Definição~\ref. Isso faz o latex não quebrar a linha.

2020-06-06 16:27 UTC, filipebraida commented on main.tex
> +\coadvisor[Prof.]{Nome do co-orientador,~M.Sc.}{}{a} % co-orientadora
Não seria legal fazzer esse lance para a banca tb?

2020-06-15 14:36 UTC, AulosRafael commented on projetofinal-dcc.cls
> +\RequirePackage[printonlyused]{acronym}
Eu estudei melhor o pacote e passei a usar somente o "acronym". Retirei os demais.
Também adicionei os comentários para seguir o padrão.

2020-06-15 14:36 UTC, AulosRafael commented on elementos-postextuais/apendice.tex
> +Seguindo a Definição \ref{def:def1} e Teorema \ref{the:the1}.
Resolvido.

2020-06-15 14:38 UTC, AulosRafael commented on main.tex
> +\coadvisor[Prof.]{Nome do co-orientador,~M.Sc.}{}{a} % co-orientadora
Neste caso não dá para aplicar porque não tem diferença quanto ao gênero, como no exemplo de "orientador" e "orientadora".

2020-12-09 17:52 UTC, filipebraida commented
@AulosRafael você fechou as modificações?

2020-12-09 18:40 UTC, AulosRafael commented
> @AulosRafael você fechou as modificações?

Está fechado.

2021-10-07 20:01 UTC, filipebraida approved these changes

2021-10-07 20:01 UTC, merged